[manager]
# sort_by = 'none'
# sort_by = 'modified'
# sort_by = 'created'
# sort_by = 'extension'
sort_by = 'alphabetical'
# sort_by = 'natural'
# sort_by = 'size'

sort_sensitive = false
sort_reverse = false
sort_dir_first = true
show_hidden = true
show_symlink = true # show the path of the symlink file point to, after the filename
scrolloff = 24 # the number of files to keep above and below the cursor when moving through the file list

[preview]
tab_size = 4

[opener]
#system_default = [
#	{for = 'macos', desc = 'Open with default application', exec = 'open "$@"', block = false, orphan = true},
#]
edit = [
	{for = 'unix', desc = 'Edit', exec = '"$EDITOR" "$@"', block = true, orphan = false},
]

[open]
rules = [
	# editable
	{name = '*.svg',   use = ['edit', 'open', 'reveal']},
	{name = '*.json',  use = ['edit', 'open', 'reveal']},
	{mime = 'text/*',  use = ['edit', 'open', 'reveal']},

	# executable
	{name = '*.dmg', use = ['open', 'reveal']},
	{name = '*.app', use = ['open', 'reveal']},
	{name = '*.exe', use = ['open', 'reveal']},

	# archive
	{mime = 'application/*', use = ['open', 'reveal']},

	# media
	{mime = 'font/*',  use = ['open', 'reveal']},
	{mime = 'video/*', use = ['open', 'reveal']},
	{mime = 'audio/*', use = ['open', 'reveal']},
	{mime = 'image/*', use = ['open', 'reveal']},

	# default
	{name = '*', use = ['open', 'edit', 'reveal']},
]

