# === Kanagawa Wave as Alacritty Theme ===
# Derived from: https//github.com/rebelot/kanagawa.nvim

# Black variants:
#   sumiInk0: #16161d
#   sumiInk1: #181820
#   sumiInk2: #1a1a22
#   sumiInk3: #1f1f28
#   sumiInk4: #2a2a37
#   sumiInk5: #363646
#   sumiInk6: #54546d

[colors.primary]
background = '#1f1f28' # sumiInk3
foreground = '#dcd7ba' # fujiWhite

[colors.normal]
black   = '#1f1f28' # sumiInk3
red     = '#c34043' # autumnRed
green   = '#76946a' # autumnGreen
yellow  = '#c0a36e' # boatYellow2
blue    = '#7e9cd8' # crystalBlue
magenta = '#957fb8' # oniViolet
cyan    = '#6a9589' # waveAqua1
white   = '#c8c093' # oldWhite

[colors.bright]
black   = '#54546d' # sumiInk6
red     = '#ff5d62' # peachRed
green   = '#98bb6c' # springGreen
yellow  = '#e6c384' # carpYellow
blue    = '#7fb4ca' # springBlue
magenta = '#938aa9' # springViolet1
cyan    = '#7aa89f' # waveAqua2
white   = '#dcd7ba' # fujiWhite

[colors.dim]
black   = '#16161d' # sumiInk0
white   = '#54546d' # sumiInk6

[colors.selection]
background = '#2d4f67' # waveBlue2
foreground = '#c8c093' # oldWhite

