# Colors (Kanagawa Wave)
# Derived from: https//github.com/rebelot/kanagawa.nvim

[colors.primary]
background = '#1f1f28' # sumiInk1
foreground = '#dcd7ba' # fujiWhite

[colors.normal]
black   = '#1f1f28' # sumiInk1
red     = '#c34043' # autumnRed
green   = '#76946a' # autumnGreen
yellow  = '#c0a36e' # boatYellow2
#yellow  = '#dca561' # autumnYellow
blue    = '#7e9cd8' # crystalBlue
#blue    = '#2d4f67' # waveBlue2
#blue    = '#658594' # dragonBlue
magenta = '#957fb8' # oniViolet
cyan    = '#6a9589' # waveAqua1
white   = '#c8c093' # oldWhite

[colors.bright]
#black   = '#727169' # fujiGray
black   = '#363646' # sumiInk3
#red     = '#e82424' # samuraiRed
red     = '#ff5d62' # peachRed
green   = '#98bb6c' # springGreen
yellow  = '#e6c384' # carpYellow
blue    = '#7fb4ca' # springBlue
magenta = '#938aa9' # springViolet1
cyan    = '#7aa89f' # waveAqua2
white   = '#dcd7ba' # fujiWhite

[colors.dim]
black   = '#16161d' # sumiInk0
white   = '#727169' # fujiGray

[colors.selection]
background = '#2d4f67' # waveBlue2
foreground = '#c8c093' # oldWhite

