# theme: pencil-dark

[colors.normal]
black   = '#212121'
red     = '#c30771'
green   = '#10a778'
yellow  = '#a89c14'
blue    = '#008ec4'
magenta = '#523c79'
cyan    = '#20a5ba'
white   = '#d9d9d9'

[colors.bright]
#black   = '#424242'  # original
black   = '#4a4a4a'  # modified
red     = '#fb007a'
green   = '#5fd7af'
yellow  = '#f3e430'
blue    = '#20bbfc'
magenta = '#6855de'
cyan    = '#4fb8cc'
white   = '#f1f1f1'

[colors.primary]
background = '#212121'
foreground = '#d9d9d9'

[colors.cursor]
text = 'CellBackground'
cursor = 'CellForeground'

