import = [
	'~/.config/alacritty/pencil-dark.theme.toml',
]

[cursor]

[cursor.style]
shape = 'Beam'  # Block / Underline / Beam
blinking = 'Always'  # Never / Off / On / Always

[mouse]
hide_when_typing = true

[font]
size = 14.0
builtin_box_drawing = false  # use built-in font for powerline symbols?

[font.normal]
#family = 'Hack Nerd Font'
family = 'FiraCode Nerd Font'
style = 'Regular'

[font.offset]
x = 1  # letter spacing
y = 2  # line spacing

[font.glyph_offset]
x = 0
y = 1

[window]
startup_mode = 'Windowed'
dynamic_padding = true  # center the content?
resize_increments = true
opacity = 1.0
blur = false

[window.padding]
x = 0
y = 0

[window.dimensions]
columns = 128
lines   = 64

[scrolling]
history = 10000
multiplier = 3  # scrolling speed

[keyboard]
bindings = [
	{key = 'Tab', mods = 'Control|Shift', action = 'SelectPreviousTab'},
	{key = 'Tab', mods = 'Control',       action = 'SelectNextTab'},
]

