# === Settings for Alacritty ===
# Copy 'default.toml' as 'local.toml' to overwrite

import = [
	'~/.config/alacritty/themes/kanagawa.toml',
	'~/.config/alacritty/default.toml',
	'~/.config/alacritty/local.toml',
]

