import = [
	'~/.config/alacritty/themes/kanagawa.toml',
]

[env]
TERM = 'alacritty'  # NOTE: 'alacritty' terminfo needs to be installed

[cursor]

[cursor.style]
shape = 'Beam'  # Block / Underline / Beam
blinking = 'Always'  # Never / Off / On / Always

[mouse]
hide_when_typing = true

[font]
size = 11.0
builtin_box_drawing = true  # use built-in font for powerline symbols?

[font.normal]
family = 'JetBrainsMonoNL Nerd Font'
style  = 'ExtraLight'
# family = 'MesloLGM Nerd Font'
# style  = 'Regular'

[font.offset]
x = 0  # letter spacing
y = 0  # line spacing

[font.glyph_offset]
x = 0
y = 0

[window]
startup_mode = 'Windowed'
dynamic_padding = false  # center the content?
resize_increments = true
opacity = 1
blur = false

[window.padding]
x = 0
y = 0

[window.dimensions]
columns = 128
lines   = 64

[scrolling]
history = 10000
multiplier = 3  # scrolling speed

[keyboard]
bindings = [
	{key = 'Tab',    mods = 'Control|Shift', action = 'SelectPreviousTab'},
	{key = 'Tab',    mods = 'Control',       action = 'SelectNextTab'},
	{key = 'Return', mods = 'Shift',         chars  = "\u001b[13;2u"},
	{key = 'Return', mods = 'Control',       chars  = "\u001b[13;5u"},
]

