# === Settings for Alacritty ===
# Copy 'default.toml' as 'local.toml' to overwrite

[general]
import = [
	'themes/kanagawa.toml',
	'default.toml',
	'local.toml',
]

[keyboard]
bindings = [
	{key = 'Tab',    mods = 'Control|Shift', action = 'SelectPreviousTab'},
	{key = 'Tab',    mods = 'Control',       action = 'SelectNextTab'},
	{key = 'Return', mods = 'Shift',         chars  = "\u001b[13;2u"},
	{key = 'Return', mods = 'Control',       chars  = "\u001b[13;5u"},
]

